### ISSUE TITLE
How can :scm be communicated for a non-lein/-boot project?

### ISSUE THREAD

**Issue by seancorfield** [cljdoc/cljdoc#139]
See https://github.com/clojure/tools.cli which has no `project.clj` file. It has `pom.xml` and `deps.edn`.

I requested https://cljdoc.xyz/d/org.clojure/tools.cli/0.4.1 and it built it (but failed, and then I couldn't view the actual failed build, nor repro) but it hasn't included a readme etc -- and says the SCM information isn't properly set up.

What needs to change in the `pom.xml` file for cljdoc to pick the SCM location up correctly?

**Comment by martinklepsch** [comment]
SCM info is generally communicated via POM files, cljdoc does not look at `project.clj` or `build.boot` at all

The pom info seems to be set for tools.cli so I'll have to look into why this hasn't been picked up correctly. It seems that something failed while cloning the repo or checking out the appropriate revision. My hunch is that this is a bug with cljdoc and the tools.cli SCM info is correct. 👍 

```xml
  <scm>
    <connection>scm:git:git@github.com:clojure/tools.cli.git</connection>
    <developerConnection>scm:git:git@github.com:clojure/tools.cli.git</developerConnection>
    <url>git@github.com:clojure/tools.cli.git</url>
    <tag>tools.cli-0.4.1</tag>
  </scm>
```

**Comment by seancorfield** [comment]
Weirdly, the failed build (5041) links to https://circleci.com/gh/martinklepsch/cljdoc-builder/5426 which seems to show success.

Thanks for looking into this. Maybe update the SCM section of the library author's instructions to clarify that cljdoc reads the `pom.xml` *only* and clarifying what should be in the POM for non-lein/non-boot projects?

**Comment by martinklepsch** [comment]
@seancorfield cljdoc analyses projects in two steps:

1. API inspection (running sandboxed on CircleCI)
2. Git integration (running on a cljdoc server)

In the case of tools.cli v0.4.1 step two failed because the tag provided in the `pom.xml` could not be found. The build for v0.4.0 works fine and [docs are available](https://cljdoc.xyz/d/org.clojure/tools.cli/0.4.0/doc/readme). 

Unfortunately that error isn't surfaced very well which I hope to address with #111 to some extent. Also in this case the UI should probably not give misleading statements like "SCM info missing".

I think if you push the tag that's specified in the `pom.xml` to GitHub the build should succeed.

**Comment by seancorfield** [comment]
Ah, that would be because the release process on Clojure's build server partially failed when I cut the 0.4.1 release -- so it got released to Maven Central but didn't tag the project. I've manually tagged the project now. Is there a way for me to ask cljdoc to rebuild tools.cli 0.4.1?

**Comment by martinklepsch** [comment]
There is a hidden button in the top right. Left of the „SCM Info missing“ note. Use the inspector if you can’t find it. Sorry that this isn’t easier to find 🙂

**Comment by seancorfield** [comment]
Found it! Rebuilt. Thank you.

**Comment by martinklepsch** [comment]
I’ll close this @seancorfield, thanks for coming by and pointing out issues with the documentation! 

Feel free to reopen if you think this isn’t addressed sufficiently.

**Comment by seancorfield** [comment]
Those changes look great. Thank you!
