### ISSUE TITLE
Cljdoc build failes when a regex is used in the arglist (as default value in :or)

### ISSUE THREAD

**Issue by IamDrowsy** [cljdoc/cljdoc#143]
I tried to generate the documentation for https://github.com/metasoarous/semantic-csv.
The [build](https://circleci.com/gh/martinklepsch/cljdoc-builder/5452#tests/containers/0) failed with 'No dispatch macro for: "'.

The reason is, that in [this function](https://github.com/metasoarous/semantic-csv/blob/4b2447175d3de501155254038133559f56de14cf/src/semantic_csv/transducers.cljc#L232) an regex is used as a default value. 

This regex ends up in the arg-list in the file produced by the analyser, that is read in again in [the runner](https://github.com/cljdoc/cljdoc/blob/67fbc69c0f0d78f32c7914dd2761307f46d0f591/modules/analysis-runner/src/cljdoc/analysis/runner.clj#L95) and causes this error (as a regex is not valid edn).

**Comment by martinklepsch** [comment]
Thanks, that’s a good catch I didn’t consider during the initial implementation. I guess this could be solved by using nippy/transit or some other serialization lib but doing so would introduce that dependency to the analysis environment which is supposed to have as little dependencies as possible in order to minimize conflicts.

Can you think of any way to make this work with stock clojure.edn? We could introduce a tuple `[:cljdoc.analysis/regex “som*+”]` and walk the structure to transform regexes but that doesn’t feel particularly elegant...

**Comment by IamDrowsy** [comment]
We also could just replace `#"som*+"` with `#regex"some*+"` and define a reader for `regex`. This might be easier than expanding it to a tuple.
I don't like walking the structure and changing it either, but I don't see any other option if we want to produce valid edn. 
Unfortunalty it's not possible to define a reader for `#"` (and even if you set a default reader `#"som*+"` throws the same error.

Also this is probalby just the tip of the iceberg as in theory any valid clojure code could be present in this place. So maybe pulling in an extra dependency is not the worst solution.

**Comment by martinklepsch** [comment]
I think if we were to introduce a dependency for serialisation we would need to properly account for the cases where:

- a project depends on a different version of that lib with potentially breaking changes
- we want to analyze different versions of the serialisation lib

This is a general problem with the analysis environment which so far has been mostly avoided by using as few dependencies as possible. Using something like [mranderson](https://github.com/benedekfazekas/mranderson) is an option to solve this but hasn't yet been set up. 

In the meantime I think walking the structure and introducing a custom reader tag might be a viable path forward?

**Comment by IamDrowsy** [comment]
To have something concrete to talk about, I implemented the reader tag version. https://github.com/IamDrowsy/cljdoc/commit/99adcacd40df560b979d48b5e180b695a62a14cb

**Comment by martinklepsch** [comment]
Oh nice, thanks for taking a stab at it. Did you check that it's working with the semantic-csv library? 

The parsed result is again written to a file (the final build artifact) in line 113 of `runner.clj`. And then in the server this file is read again where we would probably also need to supply the additional reader. [1]

I think code-wise it might also make sense to put `read-cljdoc-edn` and `serialize-cljdoc-edn` into a namespace that's in `modules/shared-utils` as those are available to the analysis environment as well as the server.

[1]: This is necessary due to an inefficiency in the runner. It launches a process for clj and cljs analysis separately but could probably do analysis for both platforms in a single run.

**Comment by IamDrowsy** [comment]
I tried to move the serialization/reading to `modules/shared-utils` but it seems that the analyzer `impl` started by the runner does not have access to the shared utils. 
I'm not sure how to add it. I've seen that the enviroment is constructed in the `util.deps.clj` but what should be added there? (I never used deps.edn before).

**Comment by martinklepsch** [comment]
You're right. I added a commit to master (60d06a7) that should make `cljdoc.util` available in the `cljdoc.analysis.impl` namespace. It's a bit of a hack but the entire environment `impl.clj` is ran in is constructed somewhat from hand so I guess it's fine. 😄

**Comment by martinklepsch** [comment]
Also sorry for pointing you to a dead end 🙃  I hope the commit linked in the previous commit makes sense. If it doesn't I'd be happy to chat about all this more because it admittedly is somewhat complex.  Just ping me in Slack and we can jump on a hangout session or something.

**Comment by IamDrowsy** [comment]
No worries :).
I made the change based on the new master and testet it with semantic-csv and one other project in the local environment. Looked good so far.
I found one more place (in `cljdoc.cli`) where the analyze result is read in again (also this time with `read-string` instead of `edn/read-string`). But while `read-string` could read in a regex without the custom tag, now with the custom tag a custom reader is needed. 
I hope there was no reason the file was read in via `read-string` instead of `edn/read-string`.

**Comment by martinklepsch** [comment]
> also this time with `read-string` instead of `edn/read-string`

Pretty sure this was just an oversight on my end. 😇

**Comment by martinklepsch** [comment]
And `semantic-csv` builds: https://cljdoc.xyz/d/semantic-csv/semantic-csv/0.2.1-alpha1

Unfortunately most of the docstrings are written in comments for marginalia... :smirk:

**Comment by martinklepsch** [comment]
Fixed via #154
