### ISSUE TITLE
Improve /builds to show some basic stats about build success rates

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#150]
Currently https://cljdoc.xyz/builds is just a basic list of stuff but it would actually be useful to have some insight into success rates of documentation builds to better notice increasing error rates after a change or similar.

Thinking of something like just a few numbers and if the error rate is elevated for some interval (standard deviation or something) make it red: 

<img width="666" alt="screen shot 2018-10-16 at 18 46 00" src="https://user-images.githubusercontent.com/97496/47032928-d59bc580-d173-11e8-9b8b-71094149d35b.png">

I know we could have proper graphs and stuff here but then we'd probably introduce some JS/dependencies and this seems like a reasonable first step. Happy to discuss though. 

In the long run we should also track the analyser version as part of builds so that we can track these metrics with respect to what analyser version is being used.

[This Tachyons example](http://tachyons.io/components/lists/slab-stat/index.html) might be helpful if you're unfamiliar with Tachyons (which is what cljdoc uses for styling).

**Comment by avichalp** [comment]
@martinklepsch Great idea. I was wondering to show the numbers if we have to change this query:

https://github.com/cljdoc/cljdoc/blob/2a56a4d8bebe40573a4238e3916909f5d1a6123c/src/cljdoc/server/build_log.clj#L64-L66

Remove the `limit`. Then calculate percent of failing / passing builds. This might cause performance issues? Because we will end up loading too many rows in memory. 

Or we can have another aggregate sql query? What do you think?

**Comment by martinklepsch** [comment]
@avichalp fair point. I think for now we're fine with just passing a high limit and doing the transformation in memory though. 

We've had around 5000 builds since 2018-05-31 (~1000/mo) and holding a thousand of these rows in memory shouldn't be a problem I think. 

If it's easier to run the numbers with plain SQL then we could do that but at least for me it would be easier to build up the stats using plain Clojure.

**Comment by avichalp** [comment]
This Make sense. Although I am not sure an arbitrary limit. How about instead of setting a huge number in the limit we update the SQL query to have a `where` clause to check current month in `analysis_received_ts`?  Then process the data in backend, compute percentages and update the Hiccup accordingly?

**Comment by martinklepsch** [comment]
Sure that works too! 🙂

Btw I would be interested in your feedback on #153 since it’s somewhat related to this issue.
