### ISSUE TITLE
Redirect https://cljdoc.xyz/d/<groupid>/<artifactid> to the latest version?

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#163]
When I was just typing URLs, I expected that 
https://cljdoc.xyz/d/reagent/reagent would take me to 
https://cljdoc.xyz/d/reagent/reagent/0.8.1, however instead the version selection page is at the root of the project. I wondered whether it would be more aesthetically pleasing to redirect to the latest version of the library and create a new `/versions` route for version selection?

**Comment by martinklepsch** [comment]
are you suggesting 
1. `https://cljdoc.xyz/d/reagent/reagent/versions` or
2. `https://cljdoc.xyz/versions/reagent/reagent`

I wanted to avoid the "route overloading" of option 1 since IIRC versions can be arbitrary strings. But we could establish that `/d/` should always try to get you to some docs as best as possible. 
It could e.g. also redirect `https://cljdoc.xyz/d/reagent` assuming identical group and artifact name.

**Comment by danielcompton** [comment]
Yeah I did think about the route overloading problem. I was suggesting 1, but looking at it now, probably 2 is better.

> It could e.g. also redirect https://cljdoc.xyz/d/reagent assuming identical group and artifact name.

Clojars does this and while it works, it does lead to some slightly confusing scenarios as there is a bit of route overloading between groups and usernames IIRC. I'd probably steer away from it personally, but don't feel strongly about it.

**Comment by martinklepsch** [comment]
> Clojars does this and while it works, it does lead to some slightly confusing scenarios as there is a bit of route overloading between groups and usernames IIRC.

Since we still have the `/d/` scoping we should be fine, maybe?
