### ISSUE TITLE
Properly set Cache-Control headers

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#181]
We're setting etag headers already (#142) but Cache-Control is probably another good thing to have.

**Comment by danielcompton** [comment]
How long are you wanting to cache things for? Is this for static assets, rendered pages, or something else?

**Comment by martinklepsch** [comment]
Not sure,  I'd have to look into what's good/common. I guess it's primarily for static assets although rendered pages could probably also be cached for a few minutes or so.

**Comment by martinklepsch** [comment]
ETag support was improved in https://github.com/cljdoc/cljdoc/commit/c154c4f1f2a500204b846cbd4a0b17502f0976a8

**Comment by danielcompton** [comment]
Think it's all yours @rvalentini 😃

**Comment by rvalentini** [comment]
Since I'm not familiar with the topic of HTTP caching, this is an excellent opportunity for me to learn something new :grin: 

I read some articles about best practices for HTTP caching and found this especially helpful: https://jakearchibald.com/2016/caching-best-practices/

The key takeaway for me here: there are two different approaches for Cache-Control

1) Immutable content + long `max-age`
* needs version/fingerprint in the resource URLs
* no revalidation necessary at all until `max-age` is reached
* cache busting when a resource changes (version/fingerprint changes) 

2) Mutable content, always server-revalidated
* Cache-Control: `no-cache` (-> forces revalidation)
* makes use of etag/last-modified headers when querying for updates
* requires a validation call before each use of the cached resource

According to the article, a mixture of both approaches (mutable content in combination with small `max-age`) is not a good idea and can lead to problems where interdependent resources can get out of sync.

Approach (1) would be better in general because we could get rid of the revalidation calls completely. The downside however would be that we have to introduce some kind of resource versioning (parcel supports something like that: https://github.com/parcel-bundler/parcel/pull/1025). Since there are actually not many static resources that we serve directly, this approach seemed a bit excessive to me. 

Approach (2) is basically what we have at the moment, just without any explicit Cache-Control header. Due to the etags, the static resources already get revalidated and the cache is used properly. For rendered pages however, we are not setting any etag so far. We use https://github.com/deps-app/ring-etag-middleware/blob/master/src/co/deps/ring_etag_middleware.clj for the etag generation, but this only supports file-based CRC32 checksum calculation at the moment. @danielcompton  Would it make sense to extend the functionality here? For rendered pages we have the stringified HTML page and could also calculate a CRC32 checksum here, right? 

Feels like there are a lot of different ways to go from here and I'm not so sure what is the best approach. I would probably stick to approach (2), avoid `max-age` and try to:

1) Get caching working for rendered pages via etag.

2) Introduce a new dedicated cache-control interceptor and set `no-cache` and maybe `public` directives explicitly (although that would probably have not much impact compared to the current state)

I think I could use a push in the right direction here :see_no_evil:

**Comment by rvalentini** [comment]
Thank you for your feedback and your detailed suggestions! 
I will go ahead and try to implement both of your suggested improvements. 

Concerning the second point (static assets), I just want to make sure that I understand you correctly. So following your implementation example, I would try the following steps:

1) Since we are currently generating the HTML completely dynamically, there is no head.html that we could give to Parcel as an entrypoint. I would create such a template head.html and adapt the Parcel build configuration accordingly. 

2) Since we are dynamically generating the contents, I would then try to use `selmer` to render this dynamic part into the new head.html.

3) Through using `memoize` we can then make sure that for the same dynamic content, we only render the head.html once.

**Comment by rvalentini** [comment]
Finally managed to come up with a working solution for this. Turned out to be a bigger change than I expected though :sweat_smile:.  I put the "filename extraction" into a new interceptor, so the static resources map is available everywhere through the context. Maybe there is a better place to do this? What do you guys think?
