### ISSUE TITLE
Automatically deploy on commits to master?

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#184]
It would be nice if commits to master automatically triggered deploys. As a contributor, it's always motivating to see your work immediately in production.

One of the issues with this will be the downtime when doing a deploy. I'm not sure how much of this can be reduced by doing things like building an Uberjar. If you had a CDN/Nginx cache sitting in front of the application then you could probably reduce the downtime further still.

You can also do some [cool stuff](https://developer.github.com/v3/guides/delivering-deployments/) with the GitHub API around handling deployments. See https://github.com/rubytogether/rubytogether.org/pull/213#event-1722187996 for what this can look like.

**Comment by martinklepsch** [comment]
> If you had a CDN/Nginx cache sitting in front of the application then you could probably reduce the downtime further still.

We do have Nginx in front of the app. Do you envision a setup where a second service is started and switched to once available? Or more like Nginx serving cached responses while the actual service is down? 

Either of these would be great improvements... 😃

**Comment by martinklepsch** [comment]
I looked a bit into how this could be achieved today. Nginx can handle this by running old and new config side by side for a bit:

> NGINX configuration is captured in configuration files. When you change a configuration file and restart NGINX to pick up the new configuration, it implements a “graceful restart”. Both the old and new copies of NGINX run side by side for a short period of time. The old processes don’t accept any new connections and terminate once all their existing connections terminate. 

I also stumbled upon [Caddy](https://caddyserver.com) which supports a [upstream directive](https://caddyserver.com/docs/proxy) that can take a port range:

> **try_duration** is how long to try selecting available upstream hosts for each request. By default, this retry is disabled ("0s"). Clients may hang for this long while the proxy tries to find an available upstream host. This value is only used if a request to the initially-selected upstream host fails.

 Another nice thing about Caddy is that it takes care of SSL certificates automatically (and perhaps is easier to test due to it's single config file approach). [Traefik](https://traefik.io) also has built-in Lets Encrypt support but seems a little more involved/complex for our use case.

--- 

I'm still not sure what the best way to cycle cljdoc processes would be.

Presumably upon deploy we would start another cljdoc process on the first free port in a given range, wait for it to become available and then terminate the existing (old) process. 

How to achieve that with systemd isn't quite apparent to me yet.

**Comment by martinklepsch** [comment]
Closed via https://github.com/cljdoc/cljdoc/commit/970c543e13bea78cd9b2c75d7563e36b85b54610 🎉
