### ISSUE TITLE
An exception occured, sorry about that!

### ISSUE THREAD

**Issue by kkinnear** [cljdoc/cljdoc#193]
I recently released a new version of zprint (0.4.11) which includes a bunch of changes so that cljdoc docs will be useful, and went to generate the docs.  I haven't interacted with cljdoc for a while, and was surprised to see that they are auto generated from the clojars upload.  You all have been busy!  Great work!

Unfortunately, the zprint docs don't work.  Now, it might well be my fault, because I messed up the `:scm` tag in the project.clj when I reset it from using my local git repo.  But it says "scm info missing", so I kind of thought that perhaps it noticed my screwup there and had handled it.  I didn't expect to see my various articles from the cljdoc.edn file, for instance.  But I thought that perhaps I'd see my regular API functions -- at least when I run (an older version) of cljdoc locally, I see the API functions even if I don't have valid `:scm` information.  But when I click on either of the namespaces on the public website, I get "An exception occured, sorry about that!"

If you think this is the result of my bad `:scm` info, please don't bother with it any more.  But if it is not, then maybe this is something worth looking into?  Thanks!

**Comment by martinklepsch** [comment]
Hey Kim, thanks for the heads up, this is indeed a bug caused by a recent change to inform users about more recent releases for the library they're looking at (#161). 

I fixed the issue in https://github.com/cljdoc/cljdoc/commit/2f0ea73ee1b778d345d454a61914a8a3061a7a06. 

It's deployed and the [zprint API docs](https://cljdoc.org/d/zprint/zprint/0.4.11/api/zprint.core) are working fine again.
