### ISSUE TITLE
Properly handle dependencies marked as optional in `pom.xml`

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#247]
We're already handling various `:scope`s but I just noticed that there's also an optional flag that can be specified for dependencies.

`io.aviso/pretty` uses this flag to specificy optional dependencies.

- [`pom.xml`](http://repo.clojars.org/io/aviso/pretty/0.1.29/pretty-0.1.29.pom)
- [Maven documentation](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html)

Potential fixes can be tested with:

```
./script/cljdoc ingest -p io.aviso/pretty -v 0.1.29
```

The code that needs modifications is here:

https://github.com/cljdoc/cljdoc/blob/eba11b37aaf2e0d48531d8b5ed40cbcf9606f49f/modules/analysis-runner/src/cljdoc/analysis/deps.clj#L48-L69

It will also require changes to `cljdoc.util.pom/dependencies` to ensure the `optional` flag is available to the function linked above.

Please also add the project to the `extended-tests.clj` file.

**Comment by IamDrowsy** [comment]
I added a small fix for this, but haven't added `io.aviso/pretty` to the extended test as there is another problem with this project.
It includes a [lein plugin ](https://github.com/AvisoNovate/pretty/blob/master/src/pretty/plugin.clj) that is analyzed, but fails because the dependency to `leiningen` is missing.
We could either try to fix this as well (not sure how though) or find a different project that uses an optional dependency.

**Comment by martinklepsch** [comment]
Hey @drowsy, thanks for contributing once again 🙂

While ideally the project would add Leiningen as an optional dependency as well we can just work around this by extending the `hardcoded-deps` map in `deps.clj`.

BTW, if you’d like some stickers send me your address via email/Slack/Twitter and I’ll send you some :)

**Comment by martinklepsch** [comment]
Just merged this and added the extra Leiningen dependency for pretty: https://github.com/cljdoc/cljdoc/commit/09076b79b98db59641b87c8b19eae7f1e38714ae
