### ISSUE TITLE
Error message does not link to related job

### ISSUE THREAD

**Issue by bhb** [cljdoc/cljdoc#253]
When a build fails, the error message is:

> Please see the build job to understand why this build failed and reach out if you aren't sure how to fix the issue.

Although the text "build job" is a link, it is not actually linked to the CI job:

`<a class="link blue">build job</a>`

Example: https://cljdoc.org/builds/8034

**Comment by martinklepsch** [comment]
Thanks Ben!

There's an exception that occurs when reading your cljdoc.edn file because it doesn't follow the expected format. I opened a PR to expound to fix it here: https://github.com/bhb/expound/pull/144

The build job link isn't working because a while ago we changed the order builds are done 

1. Git is analysed first on the cljdoc server
2. then a CircleCI build job is kicked off

So at the time the exception occurs and the build fails there isn't a build job to link to yet. The copy here needs some updating and surfacing those errors better would also be nice of course (#111).
