### ISSUE TITLE
"SCM info missing" but `scm` info is there?

### ISSUE THREAD

**Issue by f-f** [cljdoc/cljdoc#256]
Hi, and thanks for the gorgeous docs pages you make :)

I just pushed a new release of [dhall-clj to clojars](https://clojars.org/dhall-clj/versions/0.2.0), and [this is the built cljdoc page](https://cljdoc.org/d/dhall-clj/dhall-clj/0.2.0).

It looks like the README cannot be found because the "SCM info is missing", but the [`:scm` key in `project.clj`](https://github.com/f-f/dhall-clj/blob/master/project.clj#L6) is configured according to your docs.

Am I missing something?

**Comment by martinklepsch** [comment]
Hey Fabrizio! Thanks for the kind words. Also congrats on opening issue `2^8` 😄 

The issue here was that your repository contains a submodule and this wasn't properly accounted for in some of the code inspecting Git repositories. I made a change now so that submodules are basically ignored for now. This means users cannot specify files from submodules in their `cljdoc.edn` for now.

If there's demand for this I'm happy to revisit but for now this should fix your problem and save anyone else from problems who has submodules in their repos.

Thanks for taking the time to report this 🙌

**Comment by martinklepsch** [comment]
Here we go:

- https://cljdoc.org/builds/8944
- https://cljdoc.org/d/dhall-clj/dhall-clj/0.2.0/doc/readme

**Comment by f-f** [comment]
@martinklepsch amazing, many thanks for the quick fix! 👏🙌

(p.s. I'll also note that the issue number is `ff` in hex, which makes it an extra nice coincidence 😄)
