### ISSUE TITLE
Updating Articles after a release

### ISSUE THREAD

**Issue by ikitommi** [cljdoc/cljdoc#31]
Documentation might be updated after a release. Would be great if the docs could be updated after initial release to reflect those changes. At least for non-final releases like `-SNAPSHOT`, the regeneration of docs would be good.

EDIT Martin 2019-11-15: See [summary here](https://github.com/cljdoc/cljdoc/issues/31#issuecomment-554298351).

**Comment by sveri** [comment]
How about adding a key to cljdoc.edn like `:cljdoc.doc/for-release` which refers to the version that the documentation is valid for.
So a lib with version 0.3.4 has an entry in cljdoc.edn:
    {:cljdoc.doc/for-release "0.3.4"
     :cljdoc.doc/tree [["Getting Started" {:file "doc/getting-started.md"}]]}

and as long as the for-release number is not changed one can update the documenation and it refers to the already released version or whatever.

**Comment by martinklepsch** [comment]
@sveri this could work but it would require walking git revisions to find the last file that is for a given version. Also what happens if release `0.4.0` while my `cljdoc.edn` file still says `0.3.4`? 

How about the following: 

- Docs are always linked to git revisions, if you cut a release we will assume the documentation has been updated.
- If you make updates to your documentation after a release you can add some data to your cljdoc.edn:

```clojure
{:cljdoc.doc/versions {"0.3.4" "d5717d6659c37aa06ba25336aa994bd21b1b3d5a"}}
```
This tells us to look for revision `d571...` when building documentation for version `0.3.4`. 

An eventual CLI utility for cljdoc will provide functionality to do this without much manual fiddling:

```bash
cljdoc update-docs 0.3.4 $(git rev-parse HEAD)
```

This will add the required data and make a commit with the change. It might also push the current branch and trigger a build on cljdoc.

---

What do you think? Am I making it harder than it has to be? Is this good?

**Comment by ikitommi** [comment]
There are two cases:

1) new code & docs are developed, new SNAPSHOTs are pushed to clojars: if the version is a SNAPSHOT, my opinion is that cljdoc should allow docs to be updated in place, no questions or shas asked.

2) updating docs for real versions: something, but 1 could be resolved easily regardles.

**Comment by ikitommi** [comment]
for 1, the real (immutable) version number for the deployed SNAPSHOTS could be used, e.g. "deploy a new SNAPSHOT to clojars and the docs will be updated automatically".

**Comment by martinklepsch** [comment]
Agree there are two cases and that for SNAPSHOTs it's much more straightforward. That said I haven't really focused on supporting SNAPSHOTs and I think they mostly don't work at this point. Nothing fundamental but just hasn't been a priority. 

Just to understand what you're suggesting:

Whenever we get a new SNAPSHOT build, we simply use `master` for any documentation files.

Is that correct?

**Comment by ikitommi** [comment]
That would be great.

**Comment by martinklepsch** [comment]
@ikitommi -SNAPSHOTs are supported now: https://cljdoc.xyz/d/metosin/reitit/0.1.2-SNAPSHOT/doc/introduction/

**Comment by ikitommi** [comment]
Awesome! how do they get updated now?

**Comment by alex-dixon** [comment]
@ikitommi 
>  to update documentation you need to cut a new release (for now).
https://github.com/martinklepsch/cljdoc/blob/master/doc/userguide/faq.md#how-to-update-documentation

**Comment by martinklepsch** [comment]
This issue is about non-SNAPSHOT builds for which the problem still exists. I’m not sure about the right path to a solution but I’d like to keep it open for now.

**Comment by borkdude** [comment]
Updating docs after a Clojars release is something I would like to have for cljdoc, as I often find things in RELEASE notes that need improving (typos, forgot to remove -SNAPSHOT, etc.).

You could refresh docs when a user requests it with a specific SHA:
https://cljdoc.org/d/speculative/speculative/0.0.3?sha=...
But there would have to be some sort of protection/auth so not just anyone can do this.

The tag `cljdoc-0.1.4` or EDN config `{:cljdoc.doc/versions {"0.3.4" "d5717d6659c37aa06ba25336aa994bd21b1b3d5a"}}` work best from a protection standpoint.

Either way makes sense to me.

**Comment by martinklepsch** [comment]
```
(defn patch-level-info
  ;; Non API documentation should be updated with new Git revisions,
  ;; not only once tagged releases are published to Clojars
  ;; Some versioning scheme is required for this Non-API documentation
  ;; After recent discussion with @arrdem I'm thinking the following
  ;; version identifier might be best:
  ;;
  ;;     {:version "2.0.0" :patch-level 2}
  ;;
  ;; Where this means two changes have been made since the version
  ;; 2.0.0 has been tagged. Whether the patch-level is increased
  ;; with every commit or only with commits that modified the resulting
  ;; doc-bundle is to be decided.
  ;; TODO probably this should be captured in an ADR
  [^Git repo]

  ;; Seems like we need to walk the git commits here to retrieve tags in order
  ;; https://stackoverflow.com/questions/31836087/list-all-tags-in-current-branch-with-jgit
  )
```
Preserving [this bit of code](https://github.com/cljdoc/cljdoc/blob/d54cb58b20d2b4cb1e7c714b3637aa8b89956ce0/src/cljdoc/git_repo.clj#L219) here because it's being deleted as part of a cleanup/linting effort in #338.

**Comment by dijonkitchen** [comment]
Looks like it works for non-stable release like this RC: https://cljdoc.org/d/reagent/reagent/0.9.0-rc2/doc/documentation-index . Is that not enough?

**Comment by martinklepsch** [comment]
### A Quick Summary

cljdoc tries very hard that API docs and articles are "in sync", meaning that you don't see Articles that refer to unreleased APIs or similar. It does this by extracting articles from a projects Git repository at the SHA that is specified in the project release's `pom.xml`. 

This implicitly means that to fix a typo in your documentation you need to make a new release with a new `pom.xml` and the updated SHA that contains your typo fix. This obviously is a little unpractical and also creates noise for people monitoring releases via GitHub etc.

So the question here is: **how can we allow library authors to specify a new SHA for extracting articles than the one in `pom.xml`?** 

##### Proposed Solutions

1. `cljdoc.edn`: Extend the config file to somehow point to different SHAs for specific versions. One problem here is that you don't know the SHA before you make the commit so you'll need one commit for the doc change and one commit to update `cljdoc.edn.`
2. Git tags: Introduce a special tag like `cljdoc-$VERSION` to force cljdoc to use the SHA specified by this tag. Not too pretty but a reasonable solution for power users.

##### Snapshots

Mentioning just for clarity: SNAPSHOT releases are not built automatically, when they are built they use the Git projects main branch to extract articles. Builds for SNAPSHOTs can be requested via the request build page and rebuild using the hidden rebuild button. In the rebuild case they will again use the projects main branch. So for SNAPSHOTS we don't try to be in sync much.

**Comment by seancorfield** [comment]
I've run into this problem several times now after making a new release, someone (often not me) finds broken links or typos in the article documentation, and there's no way to fix it without making yet another release just for any documentation fixes -- which I'd rather not do: releases are for features/bug fixes.

The `cljdoc.edn` extension proposal (to include a version to SHA mapping) sounds fine to me. I assume it would work by 1) request a rebuild 2) cljdoc looks for `cljdoc.edn` on **master** to see if there's a matching version specified for the actual version you want to be rebuilt 3) if it finds it, it pulls that SHA version and uses that for the source of the new build. Having to make two commits seems reasonable to me: you might make a bunch of doc updates under multiple commits and _then_ decide to ask cljdoc to rebuild that version using the updated codebase, i.e., update `cljdoc.edn` and commit that.

I dislike the git tag approach since you may want to multiple rebuilds over time so you'd end up moving the tag... mutating the immutable.

Can you also make it a bit easier to figure out _how_ to request a cljdoc rebuild?

**Comment by martinklepsch** [comment]
> I dislike the git tag approach since you may want to multiple rebuilds over time so you'd end up moving the tag... mutating the immutable.

I understand this coming from using tags for releases but technically Git tags are not immutable and so I would consider this fair game? 

So far I've been leaning towards the tag approach just because it is a little more ergonomic than editing an EDN file. That said definitely willing to bend to users demand 😃

**Comment by seancorfield** [comment]
With the git tag version, what would happen if the `pom.xml` specifies a git SHA rather than a tag/version? Or is the proposal that for any known version, cljdoc would look for a tag `cljdoc-$VERSION` first, and fallback to the `pom.xml` tag/SHA if none were found?

**Comment by lread** [comment]
This feature will solve the problem of publishing doc updates but also introduce new confusion when folks forget they have set their docs to point at a specific sha.

I wonder if including the version in the doc pointer would help with this.

Given a version `1.2.4`, doc pointer defaults to sha from pom.xml, but can be overridden via doc pointer for version `1.2.4` at specified sha/tag. If doc pointer does not match current library version it would be ignored (default to sha from pom.xml). Would that work?

I haven't thought about it deeply, but the `cljdoc.edn` approach seems more straight-forward (less magicy, more deliberate) to me. Maybe something like `:override-docs {:for-version "1.2.4" :sha "shablahblah"}`. The extra commit required could be automated with a little `update-docs-for-cljdoc` script.

**Comment by seancorfield** [comment]
> This feature will solve the problem of publishing doc updates but also introduce new confusion when folks forget they have set their docs to point at a specific sha.

Since it would be on a per-version basis, I'm not sure where the confusion would be? The `cljdoc-<version>` tag would only be needed for versions where the docs need to be "ahead" of the actual version, and that would only change with a deliberate specific tag being applied (or moved).

If you publish version 1.2.3 and then update docs and tag that `cljdoc-1.2.3` to rebuild the docs, and then publish version 1.2.4 it won't alter the 1.2.3 docs -- they'll still point at that tag.

**Comment by lread** [comment]
Ah, I see, so the tag proposal does not have this issue then.

The cljdoc.edn proposal, if I understand correctly, would have the potential for the forgotten doc pointer though, wouldn't it - or maybe the proposal covers this with 
>  Extend the config file to somehow point to different SHAs for ***specific versions***

And maybe I just gave an example of how that might work.

If its all covered, ignore me, carry on. 🙂

**Comment by lread** [comment]
Sounds good to me @IGJoshua! See point 8 of #459 which suggests a `cljdoc/` prefix.

**Comment by lread** [comment]
Ok, I'm going to take a stab at this one.

Thanks to @IGJoshua and @seancorfield for some initial feedback on Slack.

Some notes on my general plan:

## Current Mechanics
At build time, for articles, cljdoc:
- slurps and stores articles (either auto-detected or explicitly listed in cljdoc.edn doc tree)
- saves a list of all git files at jar-specified-revision, these are used to decide how adjust links at render time

At render time, cljdoc renders slurped articles while adjusting any links/refs therein
- any links to articles in git repo that have been slurped will be adjusted to point back to cljdoc slurped version
- any referenced images in git repo will be at jar-specified-revision
- any links to other files in git repo will link to thoses file at jar-specified-revision

## Adjustments
For artifact version `1.2.3` git tag `cljdoc/1.2.3` (or `cljdoc/v1.2.3`) will be used for the articles-revision. In the absence of this tag, cljdoc will behave as it does today.

We'll
- slurp cljdoc.edn at articles-revision for the potentially updated doc tree 
- slurp articles in doc tree (else auto-discover) at articles-revision.
- we'll save a list of all git files at articles-revision (exact details TBD), this list will be used when adjusting links/refs in articles at render time
- api docs source links will point back to git sources at jar-specified-revision
- api docstrings... might be fine using jar-specified-revision for link adjustments, I'll think about this a bit. Not many folks use links in docstrings, but I do.  

Docs
- author guide will be updated.

Optionally
- update existing builds log presented to user noting when we have found, and are using, cljdoc version tag.

## Invoking
This new behavior will be invoked in the existing build process and via [existing build triggers](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#triggers).

**Comment by lread** [comment]
On second thought a tag format of `cljdoc-<version>` is clearer than `cljdoc/<version>`.
I liked the `/` version because it looked like a clojure namespaced thing, but these tags will end up in URLs and will be easier to see and reason about if they do not contain `/` which is also a path separator char.
