### ISSUE TITLE
Cheshire build fails

### ISSUE THREAD

**Issue by cloojure** [cljdoc/cljdoc#360]
cheshire/Cheshire v5.9.0

- [CircleCI build](https://circleci.com/gh/cljdoc/builder/9307)
- [cljdoc build](https://cljdoc.org/builds/17998)

**Comment by martinklepsch** [comment]
Thanks Alan! Please consider adding a link to the failing build or similar when reporting issues in the future. You probably have it open already anyways :) I edited the description to include links to the cljdoc and CircleCI build pages now.

For some reason it seems that the analysis loads a very old (2012) version of tools.namespace that has an [invalid namespace declaration](
https://github.com/clojure/tools.namespace/blob/e5cc4eba2e75de201b44d71e269fc9b2dcb3ac46/src/main/clojure/clojure/tools/namespace/find.clj#L9-L19
) using `import` in the `ns` form instead of the keyword `:import`:

```clj
  (import (java.io File FileReader BufferedReader PushbackReader
                   InputStreamReader)
          (java.util.jar JarFile JarEntry)))
```

Could be that switching to the new analyzer (#353) would fix this.

**Comment by SevereOverfl0w** [comment]
This is still failing with the new analyzer

https://cljdoc.org/builds/32153
https://circleci.com/gh/cljdoc/builder/23380

https://github.com/cljdoc/cljdoc-analyzer/blob/f39551ca941f221defc3abaa85633cddcf9dd90b/src/cljdoc_analyzer/deps.clj#L11-L14 tools.namespace should be added here I think

**Comment by martinklepsch** [comment]
Sounds right to me :+1:
