### ISSUE TITLE
Failing to build deps project

### ISSUE THREAD

**Issue by wilkerlucio** [cljdoc/cljdoc#391]
Hello, in one of my projects I recently deleted the `project.clj` file in favor of just using `deps.edn`. After publishing this new version the docs stop building.

Here is the build error: https://circleci.com/gh/cljdoc/builder/20916
Project home: https://github.com/wilkerlucio/wsscode-async
pom.xml file: https://github.com/wilkerlucio/wsscode-async/blob/master/pom.xml
deps tree:
```
org.clojure/clojure 1.10.1
  org.clojure/core.specs.alpha 0.2.44
  org.clojure/spec.alpha 0.2.176
org.clojure/core.async 1.1.587
  org.clojure/tools.analyzer.jvm 1.0.0
    org.clojure/tools.analyzer 1.0.0
    org.ow2.asm/asm 5.2
    org.clojure/tools.reader 1.3.2
    org.clojure/core.memoize 0.8.2
      org.clojure/core.cache 0.8.2
        org.clojure/data.priority-map 0.0.7
```

**Comment by martinklepsch** [comment]
Hey Wilker! :wave: The issue here is that we're using tools.deps `:local/root` coordinate with the jar file. For this it is required that the pom file is packaged inside the jar. This is how most Clojure tools package jars. Unfortunately it looks like pack.alpha isn't doing that.

To test if this issue is resolved you can use the following `clj` invocation:

```
clj -Sdeps '{:deps {com.wsscode/async {:local/root "/path/to/com/wsscode/async/1.0.5/async-1.0.5.jar"}}}' -Stree
```

**Comment by wilkerlucio** [comment]
Gotcha, thanks for finding it out! I'll see what I can do to make the `pom.xml` part of the package.
