### ISSUE TITLE
Fix / replace icon service 

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#410]
via #409 

> I noticed that service for icons that used in this project https://icon.now.sh/ does not work

The icon service we used seems to now be permanently disabled. Maybe we should use something else. 

https://ionicons.com/ seems decent but would mean a bit more JS. 

EDIT: An additional thing to consider with Ionicons would be that we need to add the JS file to our offline bundle so it works properly inside dash and other tools.

**Comment by lread** [comment]
@martinklepsch, instead of using an external service, what about serving some open source friendly icons from cljdoc itself?  
Would that make sense?

**Comment by lread** [comment]
Bumped into this while surfing around: https://tagliala.github.io/vectoriconsroundup/

Note that FontAwesome might be an interesting choice because it is also what AsciiDoctor uses (if enabled). Although... AsciiDoctor is currently stuck on v4 of FontAwesome and v6 is now in the works. Not sure if that really matters to us though.  As I understand it, we just need a few pretty glyphs.
