### ISSUE TITLE
cljdoc elides functions like `->File`

### ISSUE THREAD

**Issue by cloojure** [cljdoc/cljdoc#444]
I have some helper functions (predicates and converters) that operate on `java.io` objects. Examples are `File?` to test if an object is an instance of  `java.io.File`, and `->File` to convert a string or Path into a `java.io.File` object.

Codox automatically [excludes functions](https://github.com/weavejester/codox#source-files) thought to be record constructors  such as `->Foo` and `map->Foo`.  using a regex that defaults to

    :codox {:exclude-vars #"^(map)?->\p{Upper}"}
 
I have disabled this with a custom `:exclude-vars` in my `project.clj`:

     :exclude-vars       #".*IntervalClosed|.*SpliceItem|map->[A-Z].*"
 
which works [if you browse here](https://cloojure.github.io/doc/tupelo/tupelo.io.html).

but cljdoc seems to ignore this setting ([example here](https://cljdoc.org/d/tupelo/tupelo/21.03.25/api/tupelo.io)).

How can I get `cljdoc.org` to honor custom settings for `:exclude-vars`?

**Comment by lread** [comment]
Thanks for your question @cloojure.

Cljdoc does not currently allow you this level of configuration.

I don't remember anyone asking for this feature before.
I think it might be because most library authors choose to [wrap their record constructors when exposing them in an API](https://stuartsierra.com/2015/05/17/clojure-record-constructors#unnumbered-2).

**Comment by cloojure** [comment]
Hi Lee - Actually, it is not a record constructor, but a converter that
generates a `java.io.File` object.  I use the uppercase convention to
emphasize that it is a Java object.  There is a similar function `->Path`
to create a java.nio.file.Path object, plus two predicate functions `File?`
and `Path?` to perform type testing.

When using Lein, you can alter the default codox settings with an entry in
project.clj like:


  :codox {:src-dir-uri               "
http://github.com/cloojure/tupelo/blob/master/"
          :src-linenum-anchor-prefix "L"
          :source-paths              ["src/clj" "src/cljc"]
          :language                  :clojure
          :namespaces                [#"^tupelo\."]
          :exclude-vars
 #".*IntervalClosed|.*SpliceItem|map->[A-Z].*"
          }


So record constructors like `map->MyRecord` are excluded, but something
like `->File` is retained in the docs.

Would it be possible for CljDoc to respect such settings?

Thanks,
Alan

**Comment by lread** [comment]
Oh I see, it is a function you created that just happens to look like a record constructor.  Huh.
Thanks for clarifying for me.

@martinklepsch do you have any thoughts on this?

I wonder if a simpler (no new knobs to twirl) solution might be to have cljdoc analyzer respect a `^{:no-doc false}` for rare cases like these.

**Comment by cloojure** [comment]
Adding `^{:no-doc false}` metadata would be awesome.  Much easier and
fine-grained than the regex solution codox now uses in `project.clj`.

Alan

**Comment by lread** [comment]
@cloojure it actully might make sense, I'm not sure yet.  
The only reason I am hesitant about my little idea of `^{:no-doc false}` is that it might confuse other tooling because it might  be a convention that is unexpected.

**Comment by martinklepsch** [comment]
Maybe something like `^{:cljdoc/include? true}` would work? Two benefits to this that I'm seeing:

- we avoid the double negation of `no-doc false`
- namespaced under `cljdoc/` this shouldn't cause any issues with existing tooling

Might be a little confusing in the analyzer implementation as well to have `:exclude` which can be overridden but that's a bit of a different problem I guess.

**Comment by cloojure** [comment]
That works for me.  In fact, that would allow us to use the shortcut:  `^:cljdoc/include?`

**Comment by lread** [comment]
Nice to see some more discussion!

Does this mean we'd also support `^{:cljdoc-include? false}` as equivalent to `^:no-doc`?

I'm also thinking of other tooling and how this would fit in, there is, for example, an open clj-kondo issue:
https://github.com/clj-kondo/clj-kondo/issues/1197

**Comment by martinklepsch** [comment]
> Does this mean we'd also support `^{:cljdoc/include? false}` as equivalent to ^:no-doc?

Yes, that's what I've been thinking.

**Comment by lread** [comment]
I had a think about this and I wonder if introducing new vocabulary to describe a public API might muddy the waters more than it helps.

For example right now, it is pretty clear that everything (with some small exceptions as illustrated by this issue!) is included unless it is marked with `:no-doc`.  If we introduce `:cljdoc/include?` will people wonder if they need to specify `^:cljdoc/include` on everything they'd like to include in their public API? And then wonder why things they've not marked with `^:cljdoc/include` are also included?

I agree that the double negative of `^{:no-doc false}` is awkward but it would be, I expect, rarely used.

If we stick with `:no-doc`, we might have a better chance to have other tools (codox and maybe someday clj-kondo (are there other tools too?)) adapt to our new usage of this existing vocabulary. 

Those are my thoughts, happy to discuss/learn more.

**Comment by cloojure** [comment]
lread has a good point that this is an exceptional condition we are trying to correct.  It might be more analogous to the `--force` flag in many unix commands (e.g. `git mv --force a.clj b.clj`).

One might consider something like `^:force-doc`.  This allows us to describe the 3 possible states of documentation:

1. Default automatic decision (i.e. no user tags).  Algorithm decides to document or not (almost always includes doc)
2. Never doc (via `^:no-doc`).  Absolute decision by user.
3. Force doc (via `^:force-doc`)  Absolute decision by user.

**Comment by lread** [comment]
Actually.... I wonder.
We are excluding this pattern because it matches what a record constructor would create.
And nobody has asked to include record constructor vars in their docs.

But since we know the rules for record -> record constructor vars, we could more intelligently exclude these vars only when they seem to have been generated by a record.
That might work. And would avoid any special-case inclusion metadata syntax.

**Comment by cloojure** [comment]
Hi - Any thoughts on moving this forward?  I just noticed another instance of a function being silently elided from the docs (in this instance `tupelo.java-time/->Instant`, which coerces any time-like value to a `java.time/Instant` object)

**Comment by lread** [comment]
Yeah, I suppose I could take a stab at it.
I think [my idea might work for most cases](https://github.com/cljdoc/cljdoc/issues/444#issuecomment-1019591857). I'll explore it a bit deeper to see if it has legs.

**Comment by lread** [comment]
Had a little look. 

## Current understanding
My understanding is this:
1. For the record `Foo`, cljdoc wants to exclude `->Foo` and `map->Foo`.
2. For the type `Bar`, cljdoc wants to exclude `->Bar`. 

Cljdoc is succeeding at this, but it is also, (the reason this issue was raised), excluding vars not associated with a defrecord or deftype due to simplistic exclusion pattern matching.

## Observations

What is a bit odd:
1. cljdoc is including the `defrecord Foo` as a documented API var.
2. it is NOT including `deftype Bar` as a documented API var.  

Tangential questions are: 
1. why do we include defrecord `Foo` in API docs?
2. should we be including deftype `Bar` in API docs?

Also tangential, an observation: I don't think there is a way to apply metadata to a `defrecord` or `deftype` so a user cannot mark with these with `no-doc`?

I think this might mean unless a `defrecord` is in a no-doc namespace, there is currently no facility to exclude it?

## Detection

The tricky bit is that the `->` and `map->` functions are generated by a macro. I do not see anything attached to these vars to distinguish them as originating from deftype or defrecord at load-time. 

(So how does cljdoc detect defrecords? It assumes that a var that starts with `map->` followed by a capital letter results from defrecord.)

The docstrings for the generated `->` and `map->` fns are generated by the Clojure `deftype` and `defrecord` macros.
Examples:
- `Positional factory function for class metagetta_test.test_ns1.type.DefTypeTest.`
- `Factory function for class metagetta_test.test_ns1.record.DefRecordTest, taking a map of keywords to field values.`

We could also match against these docstring patterns and make assumptions.

The line/column metadata on the generated `->` and `-map->` vars does map back to the coordinates `deftype`/`deferecord`. We could take a peek back at the source and determine the origin of the generated vars.

## [rejected] Option 1 - do nothing
This means closing this issue without solving the problem it raised.

## Option 2 - improve defrecord/deftype detection by matching on generated docstring
Better than what we are currently doing. 
If someone happened to use the same docstring pattern (unlikely) we'd exclude something we should not.

## Option 3 - improve defrecord/deftype detection by looking at source code.
Look for the `defrecord`/`deftype` string in source code via positional metadata on generated fns.
This might mostly work, but I wonder about macros that might call defrecord and deftype.

## [rejected] Option 4 - introduce new metadata syntax (see old discussion above `:no-doc false` etc...)
Although I was proposing it, I find this awkward and confusing.

## Option 5 - let cljdoc lib authors specify what they want to be excluded
No magic, and explicit.
A general solution that could handle other cases where vars are generated.

We avoided this when originally looking at the problem because we wanted fewer knobs for our users to turn, but I'm thinking this is a useful knob.

My instinct would be to have lib authors add this to their `cljdoc.edn` file in their git repo.

Perhaps we could borrow from quickdoc's overrides, but include the facility to match `namespace/var` via regular expression.

Our default behaviour would be the current behaviour (for compatibility), which might be expressed as:
```Clojure
{:cljdoc/overrides [["*/(map)?->\p{Upper}"] {:no-doc true}]}
```

If a user wanted no overrides (disabling defaults):
```Clojure
{:cljdoc/overrides nil}`
;; or 
{:cljdoc/overrides []}
```

If a user wanted to exclude some specific namespaces and a few specific vars:
```Clojure
{:cljdoc/overrides [[namespace.a namespace.b namespace.c/foo namespace.c/bar] {:no-doc true}]
```

Should we allow excluding all of ns except for specific vars like so?:
```Clojure
{:cljdoc/overrides [[namespace.a] {:no-doc true}]
                    [namespace.a/seeme!] {:no-doc nil}]}
```

In the case of a library that has records and types and wants to exclude generated fns, but also wants to include its own functions that start with `->`, maybe:
```Clojure
{:cljdoc/overrides [["*/(map)?->\p{Upper}"] {:no-doc true}]
                    [tupelo.java-time/->Instant] {:no-doc nil}]}
```

Namespaces/vars that are not matched would result in a logged warning at analysis time.

It is tempting to also allow matching on other data such as docstring (ex. the generated deftype/defrecord fns have a matchable docstring pattern), but we probably do not need this extra complexity.

The vast majority of library authors would not specify `:cljdoc/overrides` but for those that need it, I'm pretty sure it would be appreciated.

Conceivably this could be used to override other analysis data, but we'll start with supporting `:no-doc`.

## Proposal
Leaning toward option 5.
Questions, ideas, and feedback are most welcome and appreciated.

**Comment by lread** [comment]
Gonna for option 2 for now.

**Comment by lread** [comment]
@cloojure, this fix is now live.
I rebuilt tupelo docs, it seems to work fine.
Lemme know if I'm right.

**Comment by cloojure** [comment]
Hi - Just saw this after deploying a new release.  It seems to be working as desired.
Thank you,
Alan

**Comment by lread** [comment]
Glad to hear it @cloojure, thanks for following up!
