### ISSUE TITLE
Add a flag to open external links in an iframe

### ISSUE THREAD

**Issue by rollacaster** [cljdoc/cljdoc#478]
With #433 it's possible to add external links to the sidebar of a documentation.

We could add a flag to the external links in `cljdoc.edn` e.g.

```
{:cljdoc.doc/tree [["Readme" {:file "README.md"}]]
 :cljdoc.doc/links [["Community Slack" {:url "https://cljdoc.org/"
                                        :embed true}]]}
```

If the flag is true, an iframe within `cljdoc` shows the content. One potential use case is embedding examples from an external code sandbox.

**Comment by lread** [comment]
Interesting idea!

A pro would be that the external site would be integrated in the cljdoc experience.
A con would be that the external site could be misinterpreted to be hosted by cljdoc.

It has been a while since I worked with iframes.  I remember them being a bit nuanced.

**Comment by corasaurus-hex** [comment]
I like the general idea, being able to pull in external resources in your pages would be _amazing_. We'd need to make sure that we limited it to specific, blessed sites, however. Otherwise someone could embed malware in our pages that exploit browser bugs or use phishing attacks (which would be against a pretty limited demographic which is nice as far as these things go).

One idea is to go with something like what dev.to does with embedding:

```
{% twitter 834439977220112384 %}
{% gist https://gist.github.com/CristinaSolana/1885435 %}
{% youtube dQw4w9WgXcQ %}
{% codepen https://codepen.io/twhite96/pen/XKqrJX %}
```

This way they control the set of sites that can be embedded, control how things are embedded, and can easily update and/or turn off sites that have issues down the road.

**Comment by rollacaster** [comment]
Thanks for your feedback. Similar to `dev.to`, it might be better to include some recipe for embedding and implement only cases which we support something similar to:

```
{:cljdoc.doc/tree [["Readme" {:file "README.md"}]]
 :cljdoc.doc/links [["Community Slack" {:url "https://youtube.com/xyz"
                                        :embed {:type :youtube}]]}
```

Though, it might be best to do nothing for some time. #433 is not even merged yet. We could wait to check if and how people will use this feature before extending it.

**Comment by lread** [comment]
@rollacaster are you ok if we close this issue?
Or maybe restate in non-technical terms as a problem cljdoc is trying to solve?

**Comment by rollacaster** [comment]
It's ok to close it 👍
