### ISSUE TITLE
Ideas & Feedback

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#64]
I'd like to gather more feedback about cljdoc to figure out what can be improved, stimulate new ideas etc. Creating this thread so I can point people to a publicly accessible place where they can easily post their comments.

**Comment by danielcompton** [comment]
* See API docs link in header maybe? On a [page](https://cljdoc.xyz/d/reagent/reagent/0.8.1/doc/documentation-index) with lots of docs, you can't see a link to any API docs above the fold. Not really sure about the solution, just noticed a possible issue
* Clicking on a far sidebar link below the fold loses my scroll position when page loads. Again most problematic on a page with lots of docs, because you can't see what you just clicked on.
* Show different 'types' of things with icons in the API docs list
* Clicking on the top level `reagent` in API docs section should show a list of namespaces and their docstrings (if any)
* Perhaps autogenerate table of contents for groupings of docs, e.g. on Reagent's page, Frequently Asked Questions should be a link in it’s own right
* Be able to sort namespace declarations alphabetically and by declaration order.
* Add some padding to `a.link dim gray f6 tr` to make it a bit easier to click

**Comment by martinklepsch** [comment]
@danielcompton thanks! 

Just FYI, I edited your comment to include references to issues if they already exist. Will do the same for any future comments. 👍

**Comment by alex-dixon** [comment]
Suppose someone added some cool new doc stuff to my project. 😄How do I rebuild the docs to reflect those changes?

I wasn't able to find instructions for this on cljdoc.xyz or the README. 

Also for the heck of it tried https://cljdoc.xyz/d/martinklepsch/cljdoc. Got "An exception occurred! Sorry about that."

**Comment by martinklepsch** [comment]
We could add a page that lists all groups/artifacts/versions. I think this might be better addressed by a Search UI (#41) but not sure yet. (via #66)

**Comment by alex-dixon** [comment]
@martinklepsch +1 #67 :)

From some of your notes:
> Imagine we could deploy functionality to support **dynadoc-style interactive examples**, clojure.spec lookup, and more for the entire Clojure/Script ecosystem.
__emphasis added__

Do you have any further thoughts on how this could be implemented? Is it something you'd like to see in the near future?

**Comment by martinklepsch** [comment]
> Do you have any further thoughts on how this could be implemented? Is it something you'd like to see in the near future?

I'd very much like to see this being worked on but there are a bunch of things that we'll need to work out first. Tried to capture that in #70.

**Comment by alex-dixon** [comment]
@martinklepsch Thanks. Good hammock issue for sure. I'm very excited about it and at the same time it makes sense if other things are higher priority.

**Comment by devurandom** [comment]
https://youtu.be/mWrvd6SE7Vg?t=1295 made me think: Since you are already analysing code from lots of libraries, maybe you could add a feature for library authors (but maybe also to point new users in the right direction) where you sort functions by their popularity. I.e. count how often a function is used by other libraries and make the most used functions more prominent, based on the assumption that they must be more important / fundamental to the use of this library.

**Comment by martinklepsch** [comment]
> maybe you could add a feature for library authors (but maybe also to point new users in the right direction) where you sort functions by their popularity

@devurandom the cljdoc analysis is currently scoped to API-level information, i.e. we know arglists and docstrings and these kinds of things but we do not have any understanding of what is going on inside a function. For this purpose a tool like https://crossclj.info is better suited for now.

**Comment by martinklepsch** [comment]
Closing this issue for now.
