### ISSUE TITLE
[Feature request] Support for plaintext docstrings

### ISSUE THREAD

**Issue by ptaoussanis** [cljdoc/cljdoc#779]
Hi there!

Thank you so much for all the work on cljdoc, it's really awesome :-)

From what I could tell from searching the [library author docs](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc), there doesn't currently seem to be any option for configuring a library's docstrings to render as fixed-width plaintext rather than Markdown.

Is that correct?

If so, is this something that has been or would potentially be considered?

Context: I author a few Clojure/Script libraries, and would like to ensure that they work well with cljdoc. Unfortunately my docstrings were written presuming fixed-width plaintext rendering, and are often messy if not outright illegible when rendered as Markdown.

It wouldn't be viable to change these now, and more importantly - I'm not personally too keen on Markdown as a docstring format since I prefer fixed-width control and formatting optimized for use at the REPL.

For folks like me, it'd be really nice if cljdoc had some mechanism for library authors to opt-in to a plaintext rendering mode.

Thanks for taking the time to read/consider - cheers! :-)

**Comment by lread** [comment]
Hi @ptaoussanis, thanks for raising an issue!

Yes, you are correct, cljdoc renders all docstrings as Markdown.

I've noticed that this typically works out fine, but for some libs, not so much.

For example https://cljdoc.org/d/org.clojure/tools.deps/0.18.1354/api/clojure.tools.deps#calc-basis renders as:
![image](https://github.com/cljdoc/cljdoc/assets/967328/7ab5b63d-e7d9-4ad9-84d5-eeb8f5236c0f)

But if we click on "raw docstring", we see the library author clearly used plaintext formatting rather than Markdown:
![image](https://github.com/cljdoc/cljdoc/assets/967328/89ac7875-4856-4cd2-8ab9-6ce7f645f293)

I think an explicit option in `cljdoc.edn` would probably make sense. 

When this option is not present, I wonder if there is some way, by looking at the docstrings, cljdoc could determine they are clearly not Markdown and automatically render as plaintext.
Not sure. Maybe that's too much magic.

We could start with an explicit option.

**Comment by ptaoussanis** [comment]
@lread Thanks for the quick & detailed reply Lee 🙏

> https://cljdoc.org/d/org.clojure/tools.deps/0.18.1354/api/clojure.tools.deps#calc-basis

Yes, that's a good example of what I'm talking about. I have a lot of docstrings that are likewise affected.

> We could start with an explicit option.

That'd be my vote (and totally sufficient in my case) 👍

**Comment by lread** [comment]
Ok @ptaoussanis, the feature is in production and ready for you to try out.

[TLDR](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#cljdoc-config); specify `:cljdoc/docstring-format :plaintext` in your `doc/cljdoc.edn`.

**Comment by ptaoussanis** [comment]
Thanks so much Lee, looks great. Really appreciate your help + the quick turn-around 🙏

**Comment by lread** [comment]
@ptaoussanis when you do get around to using this feature for a clojars published lib, please ping back here. I'd love to have a reference project that uses this feature for adhoc testing.

**Comment by ptaoussanis** [comment]
@lread Hi Lee, sorry for the delayed response.

As requested here are some libs of mine currently using the `cljdoc.edn` config:

- https://github.com/taoensso/encore
- https://github.com/taoensso/sente
- https://github.com/taoensso/nippy
- https://github.com/taoensso/tufte
- etc.

All my current and future libs will use this, it'll just take some time to update everything.

Thanks again for all your assistance, cheers!

**Comment by lread** [comment]
Thanks for following up @ptaoussanis, much appreciated!
