### ISSUE TITLE
Scroll to opened page in the left menu

### ISSUE THREAD

**Issue by tengstrand** [cljdoc/cljdoc#790]
I'm implementing support for navigating to pages (my cljdoc documentation) and some bookmark on the given page, from the command line `poly` tool, that I'm working on.

My left menu is quite long, and if I go to a page that lives at the bottom of the left menu, it would be nice if we could not just open the page and scroll to the bookmark/anchor, but also scroll to the page in the left menu (as it is now, you can't even see the selected page, you have to manually scroll to it).

The result is that you lose the context of where you are, especially when scrolling to a bookmark further down on a page, because then you don't see the heading of that page. Making the page visible in the left menu would increase the user experience.

Here is an example of the current behaviour, where `Workspace structure` isn't visible:
![image](https://github.com/cljdoc/cljdoc/assets/631272/6be666fc-dd74-472c-a112-a0246f960d33)

...but here it is:
![image](https://github.com/cljdoc/cljdoc/assets/631272/fefa68b2-522b-4e37-abc5-b2c6a44cca83)

**Comment by lread** [comment]
I had a peek and there is some client-side code that:
1. [saves sidebar scroll pos before page unload](https://github.com/cljdoc/cljdoc/blob/baafaa476a122392ef592db4212dc4a19ed19893/js/cljdoc.ts#L109-L117)
2. [restores sidebar scroll pos on page load](https://github.com/cljdoc/cljdoc/blob/baafaa476a122392ef592db4212dc4a19ed19893/js/cljdoc.ts#L93-L104) (if viewed lib is same)

I'm not entirely sure why this was an interesting thing to do.
Perhaps you navigate away, you navigate back and you don't lose your scroll pos in the sidebar?
Or maybe, in some cases, it saves your spot while navigating within a lib's docs?
Will have to understand more before I attempt to address this issue.

**Comment by tengstrand** [comment]
If I put the url in a new tab in a web browser, http://localhost:8000/d/polylith/clj-poly/0.2.18-SNAPSHOT/doc/reference/workspace-structure in this example, the problem remains (that I can't see "Workspace structure" on the left).

**Comment by lread** [comment]
Thanks @tengstrand!

So, just taking notes at this point. 

Cljdoc is indeed saving and restoring vertical scroll position in the main left nav after an item is selected. An item selection causes the entire page to be loaded.

This makes sense, but 2 things are questionable:

1. scroll position seems to jump slightly (at least in my tests with Firefox)
2. why use local storage and not session storage? I think we'd only want to restore for a session.

As to the reported issue our goal would be:
If the user is coming to cljdoc from some external source (not an internal link) then we want to scroll the nav bar to the selected item. Otherwise, preserve the current behaviour.
