### ISSUE TITLE
Ability to skip namespaces for which analysis would fail?

### ISSUE THREAD

**Issue by ptaoussanis** [cljdoc/cljdoc#807]
Hi there! No urgency on this.

From what I can tell, cljdoc currently seems to work something like this:

1. All source files are analyzed.
2. If analysis of any source file fails, the entire cljdoc fails.
3. `^:no-doc` metadata on an ns symbol doesn't appear to prevent (1).

Is that accurate?

If so, I'd like to request/propose one or more of the following (whatever's easiest):

- Provide some mechanism to exclude certain source files from analysis.
- If analysis of a source file fails, ignore that file and continue with others.
- Allow `^:no-doc` metadata on an ns to fully prevent analysis attempt.

# Context

I'm in the process of trying to get cljdoc working correctly for my various [libraries](https://www.taoensso.com/clojure/libraries).

But at least two of my libraries ([Sente](https://www.taoensso.com/sente) and [Timbre](https://www.taoensso.com/timbre)) currently cannot be built due to one or more namespaces that fail analysis.

This occurs because both Sente and Timbre include community code (server adapters, appenders) that can be troublesome to load without very specific dependencies and/or environments.

For example:

- Timbre includes an [Android appender](https://github.com/taoensso/timbre/blob/master/deploy/src/taoensso/timbre/appenders/community/android_logcat.clj)

- Sente includes an adapter that requires [specific JVM options](https://github.com/taoensso/sente/blob/6f0b513c221829c8a46d8ed4e35decab96a69055/project.clj#L33)

**Example build failure**: [job 61286](https://app.circleci.com/pipelines/github/cljdoc/builder/44911/workflows/6cdff6dc-231d-4b77-837b-e4fd6ff455bf/jobs/61286) for [Sente build #71142](https://cljdoc.org/builds/71142):

```
Could not generate Clojure documentation for taoensso.sente.server-adapters.community.nginx-clojure
```

It would be great if cljdoc would skip over failing files, and/or provide some mechanism for excluding troublesome files from analysis.

I looked through the docs and couldn't find anything relevant (besides the `^:no-doc` meta which seems to be insufficient to fully suppress an analysis attempt).

Thanks a lot!

Cheers :-)

**Comment by lread** [comment]
Hi @ptaoussanis! 

The cljdoc analyzer will not explicitly attempt to load a namespace with `:no-doc` metadata.

But... there is nothing to stop another namespace from loading a `:no-doc` namespace. 
Perhaps this is what you are experiencing?

For your Android appender example, if you'd prefer to include this namespace in your docs, you could specify [the necessary dependency as `provided`](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#getting-dependencies-right).

Another thing that might help, if your libraries do not generate their APIs at load time, is static analysis #543. This upcoming analysis option will not attempt to load any namespaces and avoid these kinds of dynamic load-time issues.

We have considered skipping over failing namespaces in the past #228. But it is trickier than it first seems because ns a can load ns b which can load ns c. And then there's the whole problem of conveying to the library author and user what was skipped and why. It felt like a bit of a support nightmare to me personally.

**Comment by lread** [comment]
Always a pleasure @ptaoussanis!

Note that the `cljdoc-<version>` tag only impacts articles and some `cljdoc.edn` settings.
We thought that having `cljdoc-<version>` impact API docs would be problematic because the sources in the artifact jar could have drifted from the sources in the git repo.
