### ISSUE TITLE
Can't search for words with - and . in them

### ISSUE THREAD

**Issue by tengstrand** [cljdoc/cljdoc#813]
When I search for a word that includes a `-` or `.` then it searches for both what's before the `.` or `-`.

For example if I search for "tools.deps" it will include pages that only have "tools" or "deps" in it.
If I search for "abc-123", it will include pages that matches both "abc" and "123", not just "abc-123".

It would be better if it only listed pages that exactly match the search string.

**Comment by lread** [comment]
There are 2 search features on cljdoc:
- library search (from main page)
- single docset search (when viewing docs for a specific library)

It's pretty clear that you are asking about single docset search but thought it best to be explicit.

In our current implementation, index terms are broken down at whitespace or punctuation.
And we currently have no phrase searching support.

Also your examples show double quotes but I'm not sure if you are proposing we implement phrase searching. Are you suggesting `"abc-123"` vs `abc-123`? I'm guessing not.

Without thinking about implementation, I think you are requesting: if my search word includes punctuation I'd like the punctuation to also match. Is that the gist of it?

Related is: #594

**Comment by corasaurus-hex** [comment]
I wasn't able to find a client-side search engine that made symbols searchable and also fit all the other requirements. I had considered writing my own but it's a large undertaking. Perhaps the situation is better now but I haven't looked.

**Comment by lread** [comment]
Thanks @corasaurus-hex!

I did a quick look-see and thought [flexsearch](https://github.com/nextapps-de/flexsearch) might be worth another gander. But I think you looked at this one? Maybe it wasn't a good fit?

We have 2 different types of text. Prose (typically English). And source code.
Finding a good strategy to satisfy both these types of text might require a bit of thought.

**Comment by corasaurus-hex** [comment]
@lread iirc flexsearch is what I went with initially and I had to abandon it because it gave bad results (duplicates and missing). it's possible that I'm misremembering or things have been remedied, however. 

The problem goes beyond just prose and source code, unfortunately. Prose can contain source code and the normal tokenization needs to be aware of that and to intelligently detect source code vs normal punctuation and do the right thing. So whatever we use needs custom tokenization of both ingested documents and search terms, and then to factor that tokenization into the resulting ranking. It's an interesting problem but a hard one.

**Comment by tengstrand** [comment]
Yes, it was the single docset search I did, and the examples was `abc-123` and `abc-123` without the apostrophes.

**Comment by lread** [comment]
@corasaurus-hex Right... Maybe we could still do something with elasticlunr before going down flexsearch rabbit holes.

I did mean an intermix of prose and code but you described this much more clearly.

We can have prose `with code snippets` and code blocks...
```clojure
(def x
  ;; with comments that might be considered prose
  "and strings that also might be considered prose"
   42)
```

Maybe we can come up with something imperfect but a bit better.
What if our tokenizer recognized terms with punctuation and gave them a heavier weight.
So `tools.deps` would be tokenized as `tools` `deps` and `tools.deps`.

We'd have to think about tokenizer rules for terms with punctuation.
For example, leading and trailing `.` characters would not be included in a term.
But a leading or trailing `*` would be. A single `*` would probably also be interesting.
We'd probably take some inspiration for interesting patterns in the [clojure core API vars](https://clojure.github.io/clojure/clojure.core-api.html).

Would also have to think about how this would affect stemming (we'd probably not want to do this for punctuated terms if this happens at index time?) but... maybe worth a few experiments?

**Comment by corasaurus-hex** [comment]
Let me see if I can find some time to spend on it this weekend and do some experiments?

**Comment by lread** [comment]
I could be out to lunch but seems interesting. If you don't pick it up I might give it a go sometime, someday...

**Comment by corasaurus-hex** [comment]
If you want to experiment, feel absolutely 1000% free. My time is really constrained these days and I haven't had much time for open source work.

**Comment by lread** [comment]
I know! I've missed you @corasaurus-hex! (but also understand! :heart:)

**Comment by lread** [comment]
I started experimenting locally on my dev box today. 
After poking around a bit things are looking... promising.
I'll want to experiment more before committing anything tho.

Highlights of my current intended strategy is:
- index punctuation in tokens, but be thoughtful about `;` and leading/trailing `,` and `.` 
- index `punctuated.tokens-as-is` but also index individual parts: `punctuated` `tokens` `as` `is`.
- if a token is all non-alphanumeric and not too long, index it too.
- give a big boost to `punctuated.tokens-as-is` matches so they'll appear first

Currently toying with:
- stop words - might disable them - they make sense for prose but not necessarily for code.
- boolean logic, might switch to AND for typed-in terms. I expect users typically type a single term, but if they type multiple terms, they are likely wanting to narrow rather than expand.
- will need to check/test overall boolean logic and how it is applied across fields. I think this should always be OR but haven't verified yet.
- more testing and poking around. 

Note to self: a good test library with vars that are non-alphanumeric is https://cljdoc.org/d/swiss-arrows/swiss-arrows

**Comment by tengstrand** [comment]
This is great, thanks!

Is it possible to also include articles in the search? 

A big majority of all text in the poly documentation lives in articles, and it feels natural to include them in the search too, e.g. (this is just about 1/3 of all articles):
![image](https://github.com/cljdoc/cljdoc/assets/631272/52f07efb-a86c-47e2-910e-dff1643e796f)

**Comment by corasaurus-hex** [comment]
Can you give me a link to the poly docs? The one I can find on cljdoc doesn't have those articles.

**Comment by lread** [comment]
@corasaurus-hex I've been helping @tengstrand on a local branch of his, I can take a peek.

@tengstrand articles should already be indexed, if they aren't, I broke something!

**Comment by corasaurus-hex** [comment]
Ahhh ok, my mistake, carry on o7

**Comment by lread** [comment]
> Ahhh ok, my mistake, carry on o7

Ya, no mistake made! Thanks for the offer to help!

**Comment by lread** [comment]
@tengstrand it seems to work fine from your issue-318 branch.

![image](https://github.com/cljdoc/cljdoc/assets/967328/704982f5-3ff5-4952-8768-7ede4f407f02)

Those DOC matches are matches in your articles.

**Comment by tengstrand** [comment]
I didn't use the latest from cljdoc, and then they didn't turn upp, but now they do!
It looks great now, thanks again!
