### ISSUE TITLE
Support devdocs.io

### ISSUE THREAD

**Issue by KingMob** [cljdoc/cljdoc#86]
I see you're planning support for Dash and Zeal? Might I humbly suggest supporting devdocs.io too for offline support? It's similar, but free.

**Comment by martinklepsch** [comment]
Happy to take a closer look at this. Can you point me to some documentation on how to integrate with devdocs.io?

**Comment by KingMob** [comment]
https://github.com/freeCodeCamp/devdocs/wiki is a good place to start. It looks like it involves writing a scraper for cljdoc.xyz. Maybe I can write one when I get a spare moment...

It looks like Zeal is both free and open source, but it doesn't support Mac (the Zeal website just says to download Dash if you have a Mac.)

**Comment by martinklepsch** [comment]
@KingMob So as far as I can tell devdocs doesn't expose the same concept of "3rd party sources" so you'd have to write a scraper for each individual one and they would all show up in the devdocs.io sidebar individually (which I'd expect them to reject since it will be very confusing to anyone not using Clojure)

![bildschirmfoto 2018-07-26 um 15 19 19](https://user-images.githubusercontent.com/97496/43264788-4cccbaa6-90e7-11e8-9e9b-7accb15c609c.png)

I'll close this issue for now but we should reconsider it once devdocs.io supports 3rd party sources in some capacity.
