### ISSUE TITLE
Hard to read Cljdoc on certain mobile phones

### ISSUE THREAD

**Issue by teodorlu** [cljdoc/cljdoc#875]
## Problem

I'm having a hard time reading Cljdoc on my phone, especially when there are code examples.

## Cljdoc screenshots from my phone

![image](https://github.com/cljdoc/cljdoc/assets/5285452/c422709d-6606-4d50-8d2c-eab5bcb9df29)
![image](https://github.com/cljdoc/cljdoc/assets/5285452/b3d60187-89d3-46de-80fe-baff478f2d7a)

## Phone & browser information

I have a Samsung S22 ultra with a 3088x1440 pixels screen. I use Firefox Mobile as my browser.

![image](https://github.com/cljdoc/cljdoc/assets/5285452/7c09db8c-4a4f-43a8-8fc1-3e43c99e4d51)

Happy to provide more info if that's useful.

## References

Slack thread where I asked about this: https://clojurians.slack.com/archives/C8V0BQ0M6/p1715190477663999

**Comment by lread** [comment]
Thanks for a very clearly written issue @teodorlu!
I'll look into strategies for small but high-resolution screens.
We are probably choosing styling based on pixels but that's no longer a good strategy.
Maybe we can switch to characters (ems) instead of pixels, or something.

**Comment by lread** [comment]
Oh, nope. We seem to be using `em` units for mobile vs. desktop styling decisions. I'll poke around more.

**Comment by lread** [comment]
I tried to emulate your scenario with Google Chrome DevTools devices, but that didn't work out so well. So, I learned how to run an Android emulator via Android Studio. And now I can see what you see!

![image](https://github.com/cljdoc/cljdoc/assets/967328/a8749ccd-643a-4ea4-b26e-2cfaffae9d7e)

So, progress!

**Comment by lread** [comment]
Cljdoc uses Tachyons for CSS (it's similar to Tailwind, but Tailwind became popular and Tachyons less so). Tachyons supports different screen sizes with CSS class naming like so:
- no suffix - default (or implicitly fine for small screens)
- `-ns` - not small - screen size is a min with of 30em
- `-m` - medium - screen size is a min width of 30em and max with of 60em (I don't think we use this one, probably because it is too specific)
- `-l` - large - screen size is a min width of 60em

This is a mobile-first design, which is cool.

Cljdoc makes desktop vs mobile layout styling decisions on this page based on using `-ns.`

I did some hacking, and the Samsung S22 Ultra screen width is approximately 30em! So on the cusp and why a desktop layout is being rendered! That said, I think cljdoc could consider < 45em small, at least for layout purposes on this page.

Options/ideas:

1. Globally redefine small to be < 45em, not small to be a >= 45em (and then medium to start at 45em, but I don't think we use medium).
2. Tweak mobile layout at < 45em without tweaking tachyons media rules. Would have to look into how this might work.
3. Allow the user to show/hide the left nav for desktop layout.
4. Allow the user to select a mobile or desktop layout. We would have to look into how to do this.
5. ??

Option 1 might be easy and sensible. I can experiment and see how this would play out on tablet-size screens. I think it'll mean we host a custom tachyons.css, which is not an unusual use case for Tachyons.

**Comment by teodorlu** [comment]
I think all options seem reasonable. Option 4 requires the user to do something, so I'd be curious if it can be avoided.

From your estimation of my screen size (30 em) and an observation that the isde bar takes about half of that (15 em), I think it makes sense to increase the boundary between phones and desktops a bit. A cutoff of 45 em (side bar taking 1/3 of the screen) makes more sense to me.

Though I'm speculating from a user's perspective - I'm not actually familiar with the code!

**Comment by lread** [comment]
Hey, thanks for chiming in @teodorlu! I'm testing out a 45em mobile/desktop cutoff now (option 1). It seems reasonable to me. I'll make the change, and I'm sure folks will let us know if they find any issue with it (I'm guessing not, but ya never know).
