### ISSUE TITLE
Client-side docset search does not match var in article when prefixed with namespace

### ISSUE THREAD

**Issue by Ramblurr** [cljdoc/cljdoc#926]
I searched for an pre-existing issue, so my apologies if this is a duplicate... it seems pretty obvious?

**Problem**

Searching in the provided search field does not return results that match the contents of pages rather than just the titles.

**Reproduce**

1. Go to https://cljdoc.org/d/metosin/reitit/0.7.2/doc/introduction
2. Paste `create-resource-handler` in the search box

**Actual Result**
![image](https://github.com/user-attachments/assets/1d158a4d-256c-4e60-b28f-936fd0810788)

**Expected Result**

* I also expect pages that have that search term (like [doc/ring/static-resources](https://cljdoc.org/d/metosin/reitit/0.7.2/doc/ring/static-resources)) to appear in the search popup

**Comment by lread** [comment]
Ah, thanks for reporting @Ramblurr!

Reitit docs are rare in that they are [made up of several modules](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#module-support). 

I'm guessing that our search feature did not take this into account. 

If you try from another project things seem to work fine. For example, https://cljdoc.org/d/rewrite-clj/rewrite-clj/1.1.48

![image](https://github.com/user-attachments/assets/2e6291d5-aed2-4095-9f23-04a963568a3c)

**Comment by lread** [comment]
Hmmm... my guess, I think, was wrong.

It could be just how we currently index words in articles.

I agree that we should return a match for article [Static Resources](https://cljdoc.org/d/metosin/reitit/0.7.2/doc/ring/static-resources) when searching for `create-resource-handler`. 

But... I just noticed that `create-resource-handler` does not exist on its own in this article, I see it prefixed as `reitit.ring/create-resource-handler`.

If I search for `reitit.ring/create-resource-handler`, cljdoc does match the Static Resources article. We should match on the var even if it is prefixed with namespace.

I'll take a peek at cljdoc's current indexing rules.

**Comment by lread** [comment]
Ahh... there is a bug in our tokenizing code. 
https://github.com/cljdoc/cljdoc/blob/36995441870710899358c4b70361dc712a4864d8/js/single-docset-search.tsx#L42-L58

We are accidentally shadowing `subTokens`. 
I don't think tokens are ever getting broken down into sub-tokens.

So, I don't think I really completely handled #813 as planned.

It looks like I managed to get searching for words with punctuation working, but sub-tokenization never really worked. 

Since there have been very few complaints, I might revisit sub-tokenizing to maybe only split on `/` (rather than punctuation like `.`, `-`, etc). I'll experiment a bit.
