### ISSUE TITLE
Weird bug when you've got a document named "changelog" under /doc

### ISSUE THREAD

**Issue by bbatsov** [cljdoc/cljdoc#98]
Just take a look here:

![image](https://user-images.githubusercontent.com/103882/44073923-bac8043a-9f96-11e8-97da-71ecb0b64673.png)

Seems the two changelog documents got conflated somehow.

**Comment by martinklepsch** [comment]
There is some code that derives articles from the files in your `doc/` or `docs/` directory. It's a 90% kind of thing and in cases like this it's generally preferable to add a `cljdoc.edn` file (see [guide](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#articles)) and specify your doctree explicitly.

The conflict arises due to this file which does not contain a title (heading) and thus the filename is used: https://github.com/nrepl/nREPL/blob/master/doc/about/changelog.md. Adding a title would fix this problem (unless it's "Changelog" 😉).

I will close this because automatic doctrees are always going to be flawed in some exotic scenarios and I really don't want to go down the rabbit hole of trying to make it perfect.

**Comment by martinklepsch** [comment]
Thanks! — and also thanks for taking the time to file those other issues. It's good feedback. 👍

**Comment by bbatsov** [comment]
I've waited for such a service for a very long time! You've did an amazing job and I'd love to help, even in such a limited capacity. :-)
